# -*- mode: python ; coding: utf-8 -*-
"""
ZenFlux Backend PyInstaller Spec (onedir mode)

打包 Python FastAPI 后端为可执行文件 + _internal/ 依赖目录。
Tauri sidecar 机制会启动此可执行文件作为后端服务。

用法:
    python -m PyInstaller zenflux-backend.spec --noconfirm --clean
"""

import os
import sys
import platform
from pathlib import Path

block_cipher = None

PROJECT_ROOT = os.path.abspath(".")

# ==================== 数据文件（打包进 bundle）====================
# 这些目录会被复制到 _MEIPASS 中，供 get_bundle_dir() 读取
datas = [
    ("config", "config"),
    ("prompts", "prompts"),
    ("instances", "instances"),
    ("skills/library", "skills/library"),
    ("skills/__init__.py", "skills"),
    ("VERSION", "."),
]

# ==================== 隐式导入 ====================
# PyInstaller 静态分析无法发现的动态导入
hiddenimports = [
    # --- 本地业务模块 ---
    "routers",
    "routers.agents",
    "routers.chat",
    "routers.conversation",
    "routers.files",
    "routers.human_confirmation",
    "routers.settings",
    "routers.skills",
    "routers.models",
    "routers.websocket",
    "services",
    "services.agent_registry",
    "services.chat_service",
    "services.confirmation_service",
    "services.conversation_service",
    "services.knowledge_service",
    "services.session_service",
    "services.settings_service",
    "services.user_task_scheduler",
    "models",
    "models.agent",
    "models.api",
    "models.chat",
    "models.chat_request",
    "models.database",
    "models.docs",
    "models.hitl",
    "models.llm",
    "models.scheduled_task",
    "models.skill",
    "models.usage",
    "tools",
    "tools.base",
    "tools.api_calling",
    "tools.browser",
    "tools.knowledge_search",
    "tools.nodes_tool",
    "tools.observe_screen",
    "tools.plan_todo_tool",
    "tools.request_human_confirmation",
    "tools.scheduled_task_tool",
    "utils",
    "utils.app_paths",
    "utils.cache_utils",
    "utils.file_handler",
    "utils.file_processor",
    "utils.instance_loader",
    "utils.json_file_store",
    "utils.json_utils",
    "utils.message_utils",
    "utils.query_utils",
    "utils.background_tasks",
    "utils.background_tasks.context",
    "utils.background_tasks.registry",
    "utils.background_tasks.scheduler",
    "utils.background_tasks.service",
    "utils.background_tasks.tasks",
    "utils.background_tasks.tasks.mem0_update",
    "utils.background_tasks.tasks.memory_flush",
    "utils.background_tasks.tasks.recommended_questions",
    "utils.background_tasks.tasks.title_generation",
    "infra",
    "infra.local_store",
    "infra.local_store.engine",
    "infra.local_store.fts",
    "infra.local_store.generic_fts",
    "infra.local_store.models",
    "infra.local_store.pools",
    "infra.local_store.session_store",
    "infra.local_store.skills_cache",
    "infra.local_store.vector",
    "infra.local_store.workspace",
    "infra.local_store.crud",
    "infra.local_store.crud.conversation",
    "infra.local_store.crud.message",
    "infra.local_store.crud.scheduled_task",
    "infra.resilience",
    "infra.resilience.circuit_breaker",
    "infra.resilience.config",
    "infra.resilience.fallback",
    "infra.resilience.retry",
    "infra.resilience.timeout",
    "infra.storage",
    "infra.storage.async_writer",
    "infra.storage.base",
    "infra.storage.batch_writer",
    "infra.storage.local",
    "infra.storage.storage_manager",
    "logger",
    "config.llm_config",
    "config.llm_config.loader",
    # --- core 模块（大量子包）---
    "core",
    "core.agent",
    "core.agent.base",
    "core.agent.content_handler",
    "core.agent.errors",
    "core.agent.factory",
    "core.agent.models",
    "core.agent.protocol",
    "core.agent.backtrack",
    "core.agent.backtrack.error_classifier",
    "core.agent.backtrack.manager",
    "core.agent.components",
    "core.agent.context",
    "core.agent.context.prompt_builder",
    "core.agent.execution",
    "core.agent.execution.protocol",
    "core.agent.execution.rvr",
    "core.agent.execution.rvrb",
    "core.agent.tools",
    "core.agent.tools.flow",
    "core.agent.tools.special",
    "core.config",
    "core.config.loader",
    "core.context",
    "core.discovery",
    "core.discovery.app_scanner",
    "core.evaluation",
    "core.evaluation.reward_attribution",
    "core.events",
    "core.events.base",
    "core.events.broadcaster",
    "core.events.content_events",
    "core.events.conversation_events",
    "core.events.dispatcher",
    "core.events.manager",
    "core.events.message_events",
    "core.events.session_events",
    "core.events.storage",
    "core.events.system_events",
    "core.events.user_events",
    "core.events.adapters",
    "core.events.adapters.base",
    "core.events.adapters.dingtalk",
    "core.events.adapters.feishu",
    "core.events.adapters.slack",
    "core.events.adapters.webhook",
    "core.guardrails",
    "core.guardrails.adaptive",
    "core.inference",
    "core.inference.semantic_inference",
    "core.knowledge",
    "core.knowledge.embeddings",
    "core.knowledge.file_indexer",
    "core.knowledge.local_search",
    "core.llm",
    "core.llm.adaptor",
    "core.llm.base",
    "core.llm.claude",
    "core.llm.gemini",
    "core.llm.health_monitor",
    "core.llm.model_registry",
    "core.llm.openai",
    "core.llm.qwen",
    "core.llm.registry",
    "core.llm.router",
    "core.llm.tool_call_utils",
    "core.memory",
    "core.memory.base",
    "core.memory.instance_memory",
    "core.memory.manager",
    "core.memory.markdown_layer",
    "core.memory.working",
    "core.memory.system",
    "core.memory.system.cache",
    "core.memory.system.skill",
    "core.memory.user",
    "core.memory.user.episodic",
    "core.memory.user.plan",
    "core.memory.user.preference",
    "core.memory.mem0",
    "core.memory.mem0.config",
    "core.memory.mem0.pool",
    "core.memory.mem0.sqlite_vec_store",
    "core.memory.mem0.extraction",
    "core.memory.mem0.extraction.extractor",
    "core.memory.mem0.retrieval",
    "core.memory.mem0.retrieval.formatter",
    "core.memory.mem0.retrieval.reranker",
    "core.memory.mem0.schemas",
    "core.memory.mem0.schemas.behavior",
    "core.memory.mem0.schemas.emotion",
    "core.memory.mem0.schemas.explicit_memory",
    "core.memory.mem0.schemas.fragment",
    "core.memory.mem0.schemas.persona",
    "core.memory.mem0.schemas.plan",
    "core.memory.mem0.update",
    "core.memory.mem0.update.aggregator",
    "core.memory.mem0.update.analyzer",
    "core.memory.mem0.update.persona_builder",
    "core.memory.mem0.update.planner",
    "core.memory.mem0.update.prompts",
    "core.memory.mem0.update.quality_control",
    "core.memory.mem0.update.reminder",
    "core.memory.mem0.update.reporter",
    "core.monitoring",
    "core.monitoring.case_converter",
    "core.monitoring.failure_case_db",
    "core.monitoring.failure_detector",
    "core.monitoring.production_monitor",
    "core.monitoring.quality_scanner",
    "core.monitoring.token_audit",
    "core.nodes",
    "core.nodes.executors",
    "core.nodes.executors.base",
    "core.nodes.executors.shell",
    "core.nodes.local",
    "core.nodes.local.base",
    "core.nodes.local.macos",
    "core.nodes.local.windows",
    "core.nodes.manager",
    "core.nodes.protocol",
    "core.orchestration",
    "core.orchestration.code_orchestrator",
    "core.orchestration.code_validator",
    "core.orchestration.pipeline_tracer",
    "core.output",
    "core.output.formatter",
    "core.planning",
    "core.planning.dag_scheduler",
    "core.planning.progress_transformer",
    "core.planning.protocol",
    "core.planning.storage",
    "core.planning.validators",
    "core.playbook",
    "core.playbook.manager",
    "core.playbook.storage",
    "core.prompt",
    "core.prompt.complexity_detector",
    "core.prompt.framework_rules",
    "core.prompt.instance_cache",
    "core.prompt.intent_prompt_generator",
    "core.prompt.llm_analyzer",
    "core.prompt.prompt_layer",
    "core.prompt.prompt_results_writer",
    "core.prompt.runtime_context_builder",
    "core.prompt.skill_prompt_builder",
    "core.routing",
    "core.routing.intent_analyzer",
    "core.routing.intent_cache",
    "core.routing.router",
    "core.routing.types",
    "core.schemas",
    "core.schemas.validator",
    "core.skill",
    "core.skill.dynamic_loader",
    "core.skill.group_registry",
    "core.skill.loader",
    "core.skill.models",
    "core.skill.os_compatibility",
    "core.state",
    "core.state.consistency_manager",
    "core.state.operation_log",
    "core.termination",
    "core.termination.adaptive",
    "core.termination.protocol",
    "core.tool",
    "core.tool.capability",
    "core.tool.capability.skill_loader",
    "core.tool.executor",
    "core.tool.llm_description",
    "core.tool.loader",
    "core.tool.registry",
    "core.tool.registry_config",
    "core.tool.selector",
    "core.tool.types",
    "core.tool.validator",
    # --- 第三方库隐式导入 ---
    "uvicorn",
    "uvicorn.logging",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",
    "uvicorn.lifespan.off",
    "fastapi",
    "pydantic",
    "pydantic.deprecated",
    "pydantic.deprecated.decorator",
    "starlette",
    "starlette.responses",
    "starlette.websockets",
    "starlette.middleware",
    "starlette.middleware.cors",
    "anyio",
    "anyio._backends",
    "anyio._backends._asyncio",
    "anthropic",
    "openai",
    "dashscope",
    "httpx",
    "httpcore",
    "h11",
    "sniffio",
    "tiktoken",
    "tiktoken_ext",
    "tiktoken_ext.openai_public",
    "numpy",
    "numpy._core",
    "numpy._core._exceptions",
    "numpy._core._methods",
    "numpy._core.multiarray",
    "numpy._core.umath",
    "numpy._core._internal",
    "numpy._core._dtype",
    "numpy._core._type_aliases",
    "numpy.core",
    "numpy.core._exceptions",
    "numpy.core._methods",
    "numpy.core.multiarray",
    "numpy.core.umath",
    "numpy.linalg",
    "numpy.fft",
    "numpy.random",
    "aiofiles",
    "aiohttp",
    "aiosqlite",
    "sqlalchemy",
    "sqlalchemy.ext.asyncio",
    "sqlalchemy.dialects.sqlite",
    "greenlet",
    "yaml",
    "json5",
    "PIL",
    "PyPDF2",
    "docx",
    "pptx",
    "openpyxl",
    "odf",
    "apscheduler",
    "apscheduler.schedulers.asyncio",
    "apscheduler.triggers.cron",
    "apscheduler.triggers.interval",
    "croniter",
    "mem0ai",
    "mem0",
    "sqlite_vec",
    "filetype",
    "multipart",
    "psutil",
    "websockets",
    "google.genai",
]

# ==================== 排除不需要的大包 ====================
excludes = [
    "tkinter",
    "matplotlib",
    "scipy",
    "pandas",
    "notebook",
    "IPython",
    "jupyter",
    "pytest",
    "pyinstaller",
    "PyInstaller",
    "_pytest",
]

# ==================== Analysis ====================
a = Analysis(
    ["main.py"],
    pathex=[PROJECT_ROOT],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="zenflux-backend",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,          # sidecar 需要 console 输出给 Tauri 读取
    disable_windowed_traceback=False,
    argv_emulation=False,
    icon=os.path.join("frontend", "src-tauri", "icons", "icon.ico"),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="zenflux-backend",
)
