// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: tool_service.proto

package zenflux

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tool_service_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_tool_service_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{7, 0}
}

type ChatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Message         string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                                                               // 用户消息（文本或JSON字符串）
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                   // 用户 ID
	ConversationId  *string                `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3,oneof" json:"conversation_id,omitempty"`                                     // 对话 ID（可选）
	MessageId       *string                `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3,oneof" json:"message_id,omitempty"`                                                    // 消息 ID（可选）
	Stream          bool                   `protobuf:"varint,5,opt,name=stream,proto3" json:"stream,omitempty"`                                                                                // 是否流式返回
	BackgroundTasks []string               `protobuf:"bytes,6,rep,name=background_tasks,json=backgroundTasks,proto3" json:"background_tasks,omitempty"`                                        // 后台任务列表
	Files           []*FileReference       `protobuf:"bytes,7,rep,name=files,proto3" json:"files,omitempty"`                                                                                   // 文件引用列表
	Variables       map[string]string      `protobuf:"bytes,8,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 前端上下文变量
	AgentId         *string                `protobuf:"bytes,9,opt,name=agent_id,json=agentId,proto3,oneof" json:"agent_id,omitempty"`                                                          // Agent 实例 ID（可选，对应 instances/ 目录名）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_tool_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatRequest) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

func (x *ChatRequest) GetMessageId() string {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return ""
}

func (x *ChatRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *ChatRequest) GetBackgroundTasks() []string {
	if x != nil {
		return x.BackgroundTasks
	}
	return nil
}

func (x *ChatRequest) GetFiles() []*FileReference {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ChatRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *ChatRequest) GetAgentId() string {
	if x != nil && x.AgentId != nil {
		return *x.AgentId
	}
	return ""
}

type FileReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        *string                `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3,oneof" json:"file_id,omitempty"`       // 文件 ID
	FileUrl       *string                `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3,oneof" json:"file_url,omitempty"`    // 文件 URL
	FileName      *string                `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3,oneof" json:"file_name,omitempty"` // 文件名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReference) Reset() {
	*x = FileReference{}
	mi := &file_tool_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReference) ProtoMessage() {}

func (x *FileReference) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReference.ProtoReflect.Descriptor instead.
func (*FileReference) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{1}
}

func (x *FileReference) GetFileId() string {
	if x != nil && x.FileId != nil {
		return *x.FileId
	}
	return ""
}

func (x *FileReference) GetFileUrl() string {
	if x != nil && x.FileUrl != nil {
		return *x.FileUrl
	}
	return ""
}

func (x *FileReference) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

type ChatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                                // 响应码
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                           // 响应消息
	TaskId         string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                               // 任务 ID（session_id）
	ConversationId *string                `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3,oneof" json:"conversation_id,omitempty"` // 对话 ID
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                             // 状态：running, completed, failed
	Result         *string                `protobuf:"bytes,6,opt,name=result,proto3,oneof" json:"result,omitempty"`                                       // 结果（JSON 字符串）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_tool_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ChatResponse) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

func (x *ChatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChatResponse) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

type ChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`       // 事件类型
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                  // 事件数据（JSON 字符串）
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                       // 时间戳
	Seq           *int32                 `protobuf:"varint,4,opt,name=seq,proto3,oneof" json:"seq,omitempty"`                             // 序列号
	EventUuid     *string                `protobuf:"bytes,5,opt,name=event_uuid,json=eventUuid,proto3,oneof" json:"event_uuid,omitempty"` // 事件 UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_tool_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{3}
}

func (x *ChatEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ChatEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ChatEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ChatEvent) GetSeq() int32 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *ChatEvent) GetEventUuid() string {
	if x != nil && x.EventUuid != nil {
		return *x.EventUuid
	}
	return ""
}

type ReconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`     // Session ID
	AfterSeq      *int32                 `protobuf:"varint,2,opt,name=after_seq,json=afterSeq,proto3,oneof" json:"after_seq,omitempty"` // 从哪个序号之后开始
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectRequest) Reset() {
	*x = ReconnectRequest{}
	mi := &file_tool_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectRequest) ProtoMessage() {}

func (x *ReconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectRequest.ProtoReflect.Descriptor instead.
func (*ReconnectRequest) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReconnectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReconnectRequest) GetAfterSeq() int32 {
	if x != nil && x.AfterSeq != nil {
		return *x.AfterSeq
	}
	return 0
}

type ChatMockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenario      string                 `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`               // 场景类型：analytics, build
	DelayMs       int32                  `protobuf:"varint,2,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"` // 事件间隔（毫秒），默认 50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMockRequest) Reset() {
	*x = ChatMockRequest{}
	mi := &file_tool_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMockRequest) ProtoMessage() {}

func (x *ChatMockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMockRequest.ProtoReflect.Descriptor instead.
func (*ChatMockRequest) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{5}
}

func (x *ChatMockRequest) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *ChatMockRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // 服务名称，空字符串表示整体状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_tool_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=zenflux.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_tool_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

type SessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusRequest) Reset() {
	*x = SessionStatusRequest{}
	mi := &file_tool_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusRequest) ProtoMessage() {}

func (x *SessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusRequest.ProtoReflect.Descriptor instead.
func (*SessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{8}
}

func (x *SessionStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId *string                `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3,oneof" json:"conversation_id,omitempty"`
	MessageId      *string                `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3,oneof" json:"message_id,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // running, completed, failed, timeout
	LastEventSeq   int32                  `protobuf:"varint,6,opt,name=last_event_seq,json=lastEventSeq,proto3" json:"last_event_seq,omitempty"`
	StartTime      string                 `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	LastHeartbeat  *string                `protobuf:"bytes,8,opt,name=last_heartbeat,json=lastHeartbeat,proto3,oneof" json:"last_heartbeat,omitempty"`
	Progress       float64                `protobuf:"fixed64,9,opt,name=progress,proto3" json:"progress,omitempty"` // 0.0-1.0
	TotalTurns     int32                  `protobuf:"varint,10,opt,name=total_turns,json=totalTurns,proto3" json:"total_turns,omitempty"`
	MessagePreview *string                `protobuf:"bytes,11,opt,name=message_preview,json=messagePreview,proto3,oneof" json:"message_preview,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionStatusResponse) Reset() {
	*x = SessionStatusResponse{}
	mi := &file_tool_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusResponse) ProtoMessage() {}

func (x *SessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusResponse.ProtoReflect.Descriptor instead.
func (*SessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{9}
}

func (x *SessionStatusResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStatusResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionStatusResponse) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

func (x *SessionStatusResponse) GetMessageId() string {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return ""
}

func (x *SessionStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionStatusResponse) GetLastEventSeq() int32 {
	if x != nil {
		return x.LastEventSeq
	}
	return 0
}

func (x *SessionStatusResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *SessionStatusResponse) GetLastHeartbeat() string {
	if x != nil && x.LastHeartbeat != nil {
		return *x.LastHeartbeat
	}
	return ""
}

func (x *SessionStatusResponse) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *SessionStatusResponse) GetTotalTurns() int32 {
	if x != nil {
		return x.TotalTurns
	}
	return 0
}

func (x *SessionStatusResponse) GetMessagePreview() string {
	if x != nil && x.MessagePreview != nil {
		return *x.MessagePreview
	}
	return ""
}

type SessionEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AfterId       *int32                 `protobuf:"varint,2,opt,name=after_id,json=afterId,proto3,oneof" json:"after_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // 默认 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEventsRequest) Reset() {
	*x = SessionEventsRequest{}
	mi := &file_tool_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEventsRequest) ProtoMessage() {}

func (x *SessionEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEventsRequest.ProtoReflect.Descriptor instead.
func (*SessionEventsRequest) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{10}
}

func (x *SessionEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEventsRequest) GetAfterId() int32 {
	if x != nil && x.AfterId != nil {
		return *x.AfterId
	}
	return 0
}

func (x *SessionEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SessionEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Events        []*ChatEvent           `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	LastEventId   int32                  `protobuf:"varint,5,opt,name=last_event_id,json=lastEventId,proto3" json:"last_event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEventsResponse) Reset() {
	*x = SessionEventsResponse{}
	mi := &file_tool_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEventsResponse) ProtoMessage() {}

func (x *SessionEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEventsResponse.ProtoReflect.Descriptor instead.
func (*SessionEventsResponse) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{11}
}

func (x *SessionEventsResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEventsResponse) GetEvents() []*ChatEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SessionEventsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SessionEventsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SessionEventsResponse) GetLastEventId() int32 {
	if x != nil {
		return x.LastEventId
	}
	return 0
}

type UserSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSessionsRequest) Reset() {
	*x = UserSessionsRequest{}
	mi := &file_tool_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSessionsRequest) ProtoMessage() {}

func (x *UserSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSessionsRequest.ProtoReflect.Descriptor instead.
func (*UserSessionsRequest) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{12}
}

func (x *UserSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Sessions      []*SessionInfo         `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSessionsResponse) Reset() {
	*x = UserSessionsResponse{}
	mi := &file_tool_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSessionsResponse) ProtoMessage() {}

func (x *UserSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSessionsResponse.ProtoReflect.Descriptor instead.
func (*UserSessionsResponse) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{13}
}

func (x *UserSessionsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *UserSessionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SessionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConversationId *string                `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3,oneof" json:"conversation_id,omitempty"`
	MessageId      *string                `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3,oneof" json:"message_id,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Progress       float64                `protobuf:"fixed64,5,opt,name=progress,proto3" json:"progress,omitempty"`
	StartTime      string                 `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	MessagePreview *string                `protobuf:"bytes,7,opt,name=message_preview,json=messagePreview,proto3,oneof" json:"message_preview,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_tool_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{14}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

func (x *SessionInfo) GetMessageId() string {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return ""
}

func (x *SessionInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionInfo) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *SessionInfo) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *SessionInfo) GetMessagePreview() string {
	if x != nil && x.MessagePreview != nil {
		return *x.MessagePreview
	}
	return ""
}

type StopSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionRequest) Reset() {
	*x = StopSessionRequest{}
	mi := &file_tool_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionRequest) ProtoMessage() {}

func (x *StopSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionRequest.ProtoReflect.Descriptor instead.
func (*StopSessionRequest) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{15}
}

func (x *StopSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StopSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StoppedAt     string                 `protobuf:"bytes,3,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionResponse) Reset() {
	*x = StopSessionResponse{}
	mi := &file_tool_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionResponse) ProtoMessage() {}

func (x *StopSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionResponse.ProtoReflect.Descriptor instead.
func (*StopSessionResponse) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{16}
}

func (x *StopSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StopSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StopSessionResponse) GetStoppedAt() string {
	if x != nil {
		return x.StoppedAt
	}
	return ""
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_tool_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{17}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type EndSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"` // 会话摘要（JSON 字符串）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_tool_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{18}
}

func (x *EndSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndSessionResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_tool_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{19}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_tool_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{20}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ToolRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ToolName       string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`                                                           // 工具名称
	InputData      string                 `protobuf:"bytes,2,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`                                                        // 输入数据（JSON 字符串）
	InvocationId   string                 `protobuf:"bytes,3,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`                                               // 调用 ID
	ConversationId string                 `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`                                         // 对话 ID（可选）
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_tool_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{21}
}

func (x *ToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolRequest) GetInputData() string {
	if x != nil {
		return x.InputData
	}
	return ""
}

func (x *ToolRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *ToolRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ToolRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ToolResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                          // 是否成功
	Result          string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`                                             // 结果（JSON 字符串）
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                               // 错误信息
	ExecutionTimeMs int32                  `protobuf:"varint,4,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"` // 执行时间（毫秒）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolResponse) Reset() {
	*x = ToolResponse{}
	mi := &file_tool_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResponse) ProtoMessage() {}

func (x *ToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResponse.ProtoReflect.Descriptor instead.
func (*ToolResponse) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{22}
}

func (x *ToolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolResponse) GetExecutionTimeMs() int32 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

type ToolChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkType     string                 `protobuf:"bytes,1,opt,name=chunk_type,json=chunkType,proto3" json:"chunk_type,omitempty"` // 块类型：stdout, stderr, result, error
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                      // 内容
	IsFinal       bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`      // 是否最终块
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolChunk) Reset() {
	*x = ToolChunk{}
	mi := &file_tool_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolChunk) ProtoMessage() {}

func (x *ToolChunk) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolChunk.ProtoReflect.Descriptor instead.
func (*ToolChunk) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{23}
}

func (x *ToolChunk) GetChunkType() string {
	if x != nil {
		return x.ChunkType
	}
	return ""
}

func (x *ToolChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ToolChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type ToolBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*ToolRequest         `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolBatchRequest) Reset() {
	*x = ToolBatchRequest{}
	mi := &file_tool_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolBatchRequest) ProtoMessage() {}

func (x *ToolBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolBatchRequest.ProtoReflect.Descriptor instead.
func (*ToolBatchRequest) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{24}
}

func (x *ToolBatchRequest) GetRequests() []*ToolRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ToolBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*ToolResponse        `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolBatchResponse) Reset() {
	*x = ToolBatchResponse{}
	mi := &file_tool_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolBatchResponse) ProtoMessage() {}

func (x *ToolBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolBatchResponse.ProtoReflect.Descriptor instead.
func (*ToolBatchResponse) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{25}
}

func (x *ToolBatchResponse) GetResponses() []*ToolResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type AgentTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                                               // 任务 ID
	UserInput      string                 `protobuf:"bytes,2,opt,name=user_input,json=userInput,proto3" json:"user_input,omitempty"`                                                      // 用户输入
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`                                       // 对话 ID
	UserId         string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                               // 用户 ID
	Context        map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 上下文信息
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentTaskRequest) Reset() {
	*x = AgentTaskRequest{}
	mi := &file_tool_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTaskRequest) ProtoMessage() {}

func (x *AgentTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTaskRequest.ProtoReflect.Descriptor instead.
func (*AgentTaskRequest) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{26}
}

func (x *AgentTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AgentTaskRequest) GetUserInput() string {
	if x != nil {
		return x.UserInput
	}
	return ""
}

func (x *AgentTaskRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AgentTaskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AgentTaskRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type AgentTaskResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Result          string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"` // 最终结果（JSON 字符串）
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Turns           int32                  `protobuf:"varint,4,opt,name=turns,proto3" json:"turns,omitempty"` // 执行轮数
	ExecutionTimeMs int32                  `protobuf:"varint,5,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentTaskResponse) Reset() {
	*x = AgentTaskResponse{}
	mi := &file_tool_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTaskResponse) ProtoMessage() {}

func (x *AgentTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTaskResponse.ProtoReflect.Descriptor instead.
func (*AgentTaskResponse) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{27}
}

func (x *AgentTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentTaskResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AgentTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentTaskResponse) GetTurns() int32 {
	if x != nil {
		return x.Turns
	}
	return 0
}

func (x *AgentTaskResponse) GetExecutionTimeMs() int32 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

type AgentTaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // 事件类型
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                            // 事件数据（JSON 字符串）
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTaskEvent) Reset() {
	*x = AgentTaskEvent{}
	mi := &file_tool_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTaskEvent) ProtoMessage() {}

func (x *AgentTaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTaskEvent.ProtoReflect.Descriptor instead.
func (*AgentTaskEvent) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{28}
}

func (x *AgentTaskEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AgentTaskEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *AgentTaskEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AgentStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentStatusRequest) Reset() {
	*x = AgentStatusRequest{}
	mi := &file_tool_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusRequest) ProtoMessage() {}

func (x *AgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusRequest.ProtoReflect.Descriptor instead.
func (*AgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{29}
}

func (x *AgentStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStatusRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type AgentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // pending, running, completed, failed
	CurrentStep   string                 `protobuf:"bytes,2,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"` // 进度 0-100
	ActiveTools   []string               `protobuf:"bytes,4,rep,name=active_tools,json=activeTools,proto3" json:"active_tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatusResponse) Reset() {
	*x = AgentStatusResponse{}
	mi := &file_tool_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusResponse) ProtoMessage() {}

func (x *AgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusResponse.ProtoReflect.Descriptor instead.
func (*AgentStatusResponse) Descriptor() ([]byte, []int) {
	return file_tool_service_proto_rawDescGZIP(), []int{30}
}

func (x *AgentStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentStatusResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *AgentStatusResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *AgentStatusResponse) GetActiveTools() []string {
	if x != nil {
		return x.ActiveTools
	}
	return nil
}

var File_tool_service_proto protoreflect.FileDescriptor

const file_tool_service_proto_rawDesc = "" +
	"\n" +
	"\x12tool_service.proto\x12\azenflux\"\xd4\x03\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12,\n" +
	"\x0fconversation_id\x18\x03 \x01(\tH\x00R\x0econversationId\x88\x01\x01\x12\"\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tH\x01R\tmessageId\x88\x01\x01\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\bR\x06stream\x12)\n" +
	"\x10background_tasks\x18\x06 \x03(\tR\x0fbackgroundTasks\x12,\n" +
	"\x05files\x18\a \x03(\v2\x16.zenflux.FileReferenceR\x05files\x12A\n" +
	"\tvariables\x18\b \x03(\v2#.zenflux.ChatRequest.VariablesEntryR\tvariables\x12\x1e\n" +
	"\bagent_id\x18\t \x01(\tH\x02R\aagentId\x88\x01\x01\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_conversation_idB\r\n" +
	"\v_message_idB\v\n" +
	"\t_agent_id\"\x96\x01\n" +
	"\rFileReference\x12\x1c\n" +
	"\afile_id\x18\x01 \x01(\tH\x00R\x06fileId\x88\x01\x01\x12\x1e\n" +
	"\bfile_url\x18\x02 \x01(\tH\x01R\afileUrl\x88\x01\x01\x12 \n" +
	"\tfile_name\x18\x03 \x01(\tH\x02R\bfileName\x88\x01\x01B\n" +
	"\n" +
	"\b_file_idB\v\n" +
	"\t_file_urlB\f\n" +
	"\n" +
	"_file_name\"\xd7\x01\n" +
	"\fChatResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12,\n" +
	"\x0fconversation_id\x18\x04 \x01(\tH\x00R\x0econversationId\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\x06result\x18\x06 \x01(\tH\x01R\x06result\x88\x01\x01B\x12\n" +
	"\x10_conversation_idB\t\n" +
	"\a_result\"\xae\x01\n" +
	"\tChatEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x15\n" +
	"\x03seq\x18\x04 \x01(\x05H\x00R\x03seq\x88\x01\x01\x12\"\n" +
	"\n" +
	"event_uuid\x18\x05 \x01(\tH\x01R\teventUuid\x88\x01\x01B\x06\n" +
	"\x04_seqB\r\n" +
	"\v_event_uuid\"a\n" +
	"\x10ReconnectRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12 \n" +
	"\tafter_seq\x18\x02 \x01(\x05H\x00R\bafterSeq\x88\x01\x01B\f\n" +
	"\n" +
	"_after_seq\"H\n" +
	"\x0fChatMockRequest\x12\x1a\n" +
	"\bscenario\x18\x01 \x01(\tR\bscenario\x12\x19\n" +
	"\bdelay_ms\x18\x02 \x01(\x05R\adelayMs\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xaa\x01\n" +
	"\x13HealthCheckResponse\x12B\n" +
	"\x06status\x18\x01 \x01(\x0e2*.zenflux.HealthCheckResponse.ServingStatusR\x06status\"O\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x03\"5\n" +
	"\x14SessionStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xdf\x03\n" +
	"\x15SessionStatusResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12,\n" +
	"\x0fconversation_id\x18\x03 \x01(\tH\x00R\x0econversationId\x88\x01\x01\x12\"\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tH\x01R\tmessageId\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12$\n" +
	"\x0elast_event_seq\x18\x06 \x01(\x05R\flastEventSeq\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\tR\tstartTime\x12*\n" +
	"\x0elast_heartbeat\x18\b \x01(\tH\x02R\rlastHeartbeat\x88\x01\x01\x12\x1a\n" +
	"\bprogress\x18\t \x01(\x01R\bprogress\x12\x1f\n" +
	"\vtotal_turns\x18\n" +
	" \x01(\x05R\n" +
	"totalTurns\x12,\n" +
	"\x0fmessage_preview\x18\v \x01(\tH\x03R\x0emessagePreview\x88\x01\x01B\x12\n" +
	"\x10_conversation_idB\r\n" +
	"\v_message_idB\x11\n" +
	"\x0f_last_heartbeatB\x12\n" +
	"\x10_message_preview\"x\n" +
	"\x14SessionEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1e\n" +
	"\bafter_id\x18\x02 \x01(\x05H\x00R\aafterId\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limitB\v\n" +
	"\t_after_id\"\xb7\x01\n" +
	"\x15SessionEventsResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12*\n" +
	"\x06events\x18\x02 \x03(\v2\x12.zenflux.ChatEventR\x06events\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\x12\"\n" +
	"\rlast_event_id\x18\x05 \x01(\x05R\vlastEventId\".\n" +
	"\x13UserSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"w\n" +
	"\x14UserSessionsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x120\n" +
	"\bsessions\x18\x02 \x03(\v2\x14.zenflux.SessionInfoR\bsessions\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\xb6\x02\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12,\n" +
	"\x0fconversation_id\x18\x02 \x01(\tH\x00R\x0econversationId\x88\x01\x01\x12\"\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tH\x01R\tmessageId\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x01R\bprogress\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\tR\tstartTime\x12,\n" +
	"\x0fmessage_preview\x18\a \x01(\tH\x02R\x0emessagePreview\x88\x01\x01B\x12\n" +
	"\x10_conversation_idB\r\n" +
	"\v_message_idB\x12\n" +
	"\x10_message_preview\"3\n" +
	"\x12StopSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"k\n" +
	"\x13StopSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"stopped_at\x18\x03 \x01(\tR\tstoppedAt\"2\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"M\n" +
	"\x12EndSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\"\x15\n" +
	"\x13ListSessionsRequest\"^\n" +
	"\x14ListSessionsResponse\x120\n" +
	"\bsessions\x18\x01 \x03(\v2\x14.zenflux.SessionInfoR\bsessions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x94\x02\n" +
	"\vToolRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"input_data\x18\x02 \x01(\tR\tinputData\x12#\n" +
	"\rinvocation_id\x18\x03 \x01(\tR\finvocationId\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\tR\x0econversationId\x12>\n" +
	"\bmetadata\x18\x05 \x03(\v2\".zenflux.ToolRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\fToolResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12*\n" +
	"\x11execution_time_ms\x18\x04 \x01(\x05R\x0fexecutionTimeMs\"_\n" +
	"\tToolChunk\x12\x1d\n" +
	"\n" +
	"chunk_type\x18\x01 \x01(\tR\tchunkType\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\"D\n" +
	"\x10ToolBatchRequest\x120\n" +
	"\brequests\x18\x01 \x03(\v2\x14.zenflux.ToolRequestR\brequests\"H\n" +
	"\x11ToolBatchResponse\x123\n" +
	"\tresponses\x18\x01 \x03(\v2\x15.zenflux.ToolResponseR\tresponses\"\x8a\x02\n" +
	"\x10AgentTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"user_input\x18\x02 \x01(\tR\tuserInput\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12@\n" +
	"\acontext\x18\x05 \x03(\v2&.zenflux.AgentTaskRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x01\n" +
	"\x11AgentTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x14\n" +
	"\x05turns\x18\x04 \x01(\x05R\x05turns\x12*\n" +
	"\x11execution_time_ms\x18\x05 \x01(\x05R\x0fexecutionTimeMs\"a\n" +
	"\x0eAgentTaskEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"X\n" +
	"\x12AgentStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\"\x8f\x01\n" +
	"\x13AgentStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x02 \x01(\tR\vcurrentStep\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12!\n" +
	"\factive_tools\x18\x04 \x03(\tR\vactiveTools2\x92\x01\n" +
	"\x06Health\x12B\n" +
	"\x05Check\x12\x1b.zenflux.HealthCheckRequest\x1a\x1c.zenflux.HealthCheckResponse\x12D\n" +
	"\x05Watch\x12\x1b.zenflux.HealthCheckRequest\x1a\x1c.zenflux.HealthCheckResponse0\x012\x82\x02\n" +
	"\vChatService\x123\n" +
	"\x04Chat\x12\x14.zenflux.ChatRequest\x1a\x15.zenflux.ChatResponse\x128\n" +
	"\n" +
	"ChatStream\x12\x14.zenflux.ChatRequest\x1a\x12.zenflux.ChatEvent0\x01\x12B\n" +
	"\x0fReconnectStream\x12\x19.zenflux.ReconnectRequest\x1a\x12.zenflux.ChatEvent0\x01\x12@\n" +
	"\x0eChatMockStream\x12\x18.zenflux.ChatMockRequest\x1a\x12.zenflux.ChatEvent0\x012\xe4\x03\n" +
	"\x0eSessionService\x12Q\n" +
	"\x10GetSessionStatus\x12\x1d.zenflux.SessionStatusRequest\x1a\x1e.zenflux.SessionStatusResponse\x12Q\n" +
	"\x10GetSessionEvents\x12\x1d.zenflux.SessionEventsRequest\x1a\x1e.zenflux.SessionEventsResponse\x12N\n" +
	"\x0fGetUserSessions\x12\x1c.zenflux.UserSessionsRequest\x1a\x1d.zenflux.UserSessionsResponse\x12H\n" +
	"\vStopSession\x12\x1b.zenflux.StopSessionRequest\x1a\x1c.zenflux.StopSessionResponse\x12E\n" +
	"\n" +
	"EndSession\x12\x1a.zenflux.EndSessionRequest\x1a\x1b.zenflux.EndSessionResponse\x12K\n" +
	"\fListSessions\x12\x1c.zenflux.ListSessionsRequest\x1a\x1d.zenflux.ListSessionsResponse2\xd5\x01\n" +
	"\vToolService\x12:\n" +
	"\vExecuteTool\x12\x14.zenflux.ToolRequest\x1a\x15.zenflux.ToolResponse\x12?\n" +
	"\x11ExecuteToolStream\x12\x14.zenflux.ToolRequest\x1a\x12.zenflux.ToolChunk0\x01\x12I\n" +
	"\x10ExecuteToolBatch\x12\x19.zenflux.ToolBatchRequest\x1a\x1a.zenflux.ToolBatchResponse2\xec\x01\n" +
	"\fAgentService\x12D\n" +
	"\vExecuteTask\x12\x19.zenflux.AgentTaskRequest\x1a\x1a.zenflux.AgentTaskResponse\x12I\n" +
	"\x11ExecuteTaskStream\x12\x19.zenflux.AgentTaskRequest\x1a\x17.zenflux.AgentTaskEvent0\x01\x12K\n" +
	"\x0eGetAgentStatus\x12\x1b.zenflux.AgentStatusRequest\x1a\x1c.zenflux.AgentStatusResponseB,Z*github.com/zenflux/agent-client-go/zenfluxb\x06proto3"

var (
	file_tool_service_proto_rawDescOnce sync.Once
	file_tool_service_proto_rawDescData []byte
)

func file_tool_service_proto_rawDescGZIP() []byte {
	file_tool_service_proto_rawDescOnce.Do(func() {
		file_tool_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tool_service_proto_rawDesc), len(file_tool_service_proto_rawDesc)))
	})
	return file_tool_service_proto_rawDescData
}

var file_tool_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tool_service_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_tool_service_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: zenflux.HealthCheckResponse.ServingStatus
	(*ChatRequest)(nil),                    // 1: zenflux.ChatRequest
	(*FileReference)(nil),                  // 2: zenflux.FileReference
	(*ChatResponse)(nil),                   // 3: zenflux.ChatResponse
	(*ChatEvent)(nil),                      // 4: zenflux.ChatEvent
	(*ReconnectRequest)(nil),               // 5: zenflux.ReconnectRequest
	(*ChatMockRequest)(nil),                // 6: zenflux.ChatMockRequest
	(*HealthCheckRequest)(nil),             // 7: zenflux.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 8: zenflux.HealthCheckResponse
	(*SessionStatusRequest)(nil),           // 9: zenflux.SessionStatusRequest
	(*SessionStatusResponse)(nil),          // 10: zenflux.SessionStatusResponse
	(*SessionEventsRequest)(nil),           // 11: zenflux.SessionEventsRequest
	(*SessionEventsResponse)(nil),          // 12: zenflux.SessionEventsResponse
	(*UserSessionsRequest)(nil),            // 13: zenflux.UserSessionsRequest
	(*UserSessionsResponse)(nil),           // 14: zenflux.UserSessionsResponse
	(*SessionInfo)(nil),                    // 15: zenflux.SessionInfo
	(*StopSessionRequest)(nil),             // 16: zenflux.StopSessionRequest
	(*StopSessionResponse)(nil),            // 17: zenflux.StopSessionResponse
	(*EndSessionRequest)(nil),              // 18: zenflux.EndSessionRequest
	(*EndSessionResponse)(nil),             // 19: zenflux.EndSessionResponse
	(*ListSessionsRequest)(nil),            // 20: zenflux.ListSessionsRequest
	(*ListSessionsResponse)(nil),           // 21: zenflux.ListSessionsResponse
	(*ToolRequest)(nil),                    // 22: zenflux.ToolRequest
	(*ToolResponse)(nil),                   // 23: zenflux.ToolResponse
	(*ToolChunk)(nil),                      // 24: zenflux.ToolChunk
	(*ToolBatchRequest)(nil),               // 25: zenflux.ToolBatchRequest
	(*ToolBatchResponse)(nil),              // 26: zenflux.ToolBatchResponse
	(*AgentTaskRequest)(nil),               // 27: zenflux.AgentTaskRequest
	(*AgentTaskResponse)(nil),              // 28: zenflux.AgentTaskResponse
	(*AgentTaskEvent)(nil),                 // 29: zenflux.AgentTaskEvent
	(*AgentStatusRequest)(nil),             // 30: zenflux.AgentStatusRequest
	(*AgentStatusResponse)(nil),            // 31: zenflux.AgentStatusResponse
	nil,                                    // 32: zenflux.ChatRequest.VariablesEntry
	nil,                                    // 33: zenflux.ToolRequest.MetadataEntry
	nil,                                    // 34: zenflux.AgentTaskRequest.ContextEntry
}
var file_tool_service_proto_depIdxs = []int32{
	2,  // 0: zenflux.ChatRequest.files:type_name -> zenflux.FileReference
	32, // 1: zenflux.ChatRequest.variables:type_name -> zenflux.ChatRequest.VariablesEntry
	0,  // 2: zenflux.HealthCheckResponse.status:type_name -> zenflux.HealthCheckResponse.ServingStatus
	4,  // 3: zenflux.SessionEventsResponse.events:type_name -> zenflux.ChatEvent
	15, // 4: zenflux.UserSessionsResponse.sessions:type_name -> zenflux.SessionInfo
	15, // 5: zenflux.ListSessionsResponse.sessions:type_name -> zenflux.SessionInfo
	33, // 6: zenflux.ToolRequest.metadata:type_name -> zenflux.ToolRequest.MetadataEntry
	22, // 7: zenflux.ToolBatchRequest.requests:type_name -> zenflux.ToolRequest
	23, // 8: zenflux.ToolBatchResponse.responses:type_name -> zenflux.ToolResponse
	34, // 9: zenflux.AgentTaskRequest.context:type_name -> zenflux.AgentTaskRequest.ContextEntry
	7,  // 10: zenflux.Health.Check:input_type -> zenflux.HealthCheckRequest
	7,  // 11: zenflux.Health.Watch:input_type -> zenflux.HealthCheckRequest
	1,  // 12: zenflux.ChatService.Chat:input_type -> zenflux.ChatRequest
	1,  // 13: zenflux.ChatService.ChatStream:input_type -> zenflux.ChatRequest
	5,  // 14: zenflux.ChatService.ReconnectStream:input_type -> zenflux.ReconnectRequest
	6,  // 15: zenflux.ChatService.ChatMockStream:input_type -> zenflux.ChatMockRequest
	9,  // 16: zenflux.SessionService.GetSessionStatus:input_type -> zenflux.SessionStatusRequest
	11, // 17: zenflux.SessionService.GetSessionEvents:input_type -> zenflux.SessionEventsRequest
	13, // 18: zenflux.SessionService.GetUserSessions:input_type -> zenflux.UserSessionsRequest
	16, // 19: zenflux.SessionService.StopSession:input_type -> zenflux.StopSessionRequest
	18, // 20: zenflux.SessionService.EndSession:input_type -> zenflux.EndSessionRequest
	20, // 21: zenflux.SessionService.ListSessions:input_type -> zenflux.ListSessionsRequest
	22, // 22: zenflux.ToolService.ExecuteTool:input_type -> zenflux.ToolRequest
	22, // 23: zenflux.ToolService.ExecuteToolStream:input_type -> zenflux.ToolRequest
	25, // 24: zenflux.ToolService.ExecuteToolBatch:input_type -> zenflux.ToolBatchRequest
	27, // 25: zenflux.AgentService.ExecuteTask:input_type -> zenflux.AgentTaskRequest
	27, // 26: zenflux.AgentService.ExecuteTaskStream:input_type -> zenflux.AgentTaskRequest
	30, // 27: zenflux.AgentService.GetAgentStatus:input_type -> zenflux.AgentStatusRequest
	8,  // 28: zenflux.Health.Check:output_type -> zenflux.HealthCheckResponse
	8,  // 29: zenflux.Health.Watch:output_type -> zenflux.HealthCheckResponse
	3,  // 30: zenflux.ChatService.Chat:output_type -> zenflux.ChatResponse
	4,  // 31: zenflux.ChatService.ChatStream:output_type -> zenflux.ChatEvent
	4,  // 32: zenflux.ChatService.ReconnectStream:output_type -> zenflux.ChatEvent
	4,  // 33: zenflux.ChatService.ChatMockStream:output_type -> zenflux.ChatEvent
	10, // 34: zenflux.SessionService.GetSessionStatus:output_type -> zenflux.SessionStatusResponse
	12, // 35: zenflux.SessionService.GetSessionEvents:output_type -> zenflux.SessionEventsResponse
	14, // 36: zenflux.SessionService.GetUserSessions:output_type -> zenflux.UserSessionsResponse
	17, // 37: zenflux.SessionService.StopSession:output_type -> zenflux.StopSessionResponse
	19, // 38: zenflux.SessionService.EndSession:output_type -> zenflux.EndSessionResponse
	21, // 39: zenflux.SessionService.ListSessions:output_type -> zenflux.ListSessionsResponse
	23, // 40: zenflux.ToolService.ExecuteTool:output_type -> zenflux.ToolResponse
	24, // 41: zenflux.ToolService.ExecuteToolStream:output_type -> zenflux.ToolChunk
	26, // 42: zenflux.ToolService.ExecuteToolBatch:output_type -> zenflux.ToolBatchResponse
	28, // 43: zenflux.AgentService.ExecuteTask:output_type -> zenflux.AgentTaskResponse
	29, // 44: zenflux.AgentService.ExecuteTaskStream:output_type -> zenflux.AgentTaskEvent
	31, // 45: zenflux.AgentService.GetAgentStatus:output_type -> zenflux.AgentStatusResponse
	28, // [28:46] is the sub-list for method output_type
	10, // [10:28] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_tool_service_proto_init() }
func file_tool_service_proto_init() {
	if File_tool_service_proto != nil {
		return
	}
	file_tool_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_tool_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_tool_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_tool_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_tool_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_tool_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_tool_service_proto_msgTypes[10].OneofWrappers = []any{}
	file_tool_service_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tool_service_proto_rawDesc), len(file_tool_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_tool_service_proto_goTypes,
		DependencyIndexes: file_tool_service_proto_depIdxs,
		EnumInfos:         file_tool_service_proto_enumTypes,
		MessageInfos:      file_tool_service_proto_msgTypes,
	}.Build()
	File_tool_service_proto = out.File
	file_tool_service_proto_goTypes = nil
	file_tool_service_proto_depIdxs = nil
}
