// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: tool_service.proto

package zenflux

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Health_Check_FullMethodName = "/zenflux.Health/Check"
	Health_Watch_FullMethodName = "/zenflux.Health/Watch"
)

// HealthClient is the client API for Health service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== Health 服务（健康检查） ====================
type HealthClient interface {
	// 检查服务健康状态
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// 监听服务健康状态变化（流式）
	Watch(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HealthCheckResponse], error)
}

type healthClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthClient(cc grpc.ClientConnInterface) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, Health_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) Watch(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HealthCheckResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Health_ServiceDesc.Streams[0], Health_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HealthCheckRequest, HealthCheckResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Health_WatchClient = grpc.ServerStreamingClient[HealthCheckResponse]

// HealthServer is the server API for Health service.
// All implementations must embed UnimplementedHealthServer
// for forward compatibility.
//
// ==================== Health 服务（健康检查） ====================
type HealthServer interface {
	// 检查服务健康状态
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// 监听服务健康状态变化（流式）
	Watch(*HealthCheckRequest, grpc.ServerStreamingServer[HealthCheckResponse]) error
	mustEmbedUnimplementedHealthServer()
}

// UnimplementedHealthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServer struct{}

func (UnimplementedHealthServer) Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedHealthServer) Watch(*HealthCheckRequest, grpc.ServerStreamingServer[HealthCheckResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedHealthServer) mustEmbedUnimplementedHealthServer() {}
func (UnimplementedHealthServer) testEmbeddedByValue()                {}

// UnsafeHealthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServer will
// result in compilation errors.
type UnsafeHealthServer interface {
	mustEmbedUnimplementedHealthServer()
}

func RegisterHealthServer(s grpc.ServiceRegistrar, srv HealthServer) {
	// If the following call panics, it indicates UnimplementedHealthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Health_ServiceDesc, srv)
}

func _Health_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Health_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HealthCheckRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HealthServer).Watch(m, &grpc.GenericServerStream[HealthCheckRequest, HealthCheckResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Health_WatchServer = grpc.ServerStreamingServer[HealthCheckResponse]

// Health_ServiceDesc is the grpc.ServiceDesc for Health service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Health_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zenflux.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Health_Check_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Health_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tool_service.proto",
}

const (
	ChatService_Chat_FullMethodName            = "/zenflux.ChatService/Chat"
	ChatService_ChatStream_FullMethodName      = "/zenflux.ChatService/ChatStream"
	ChatService_ReconnectStream_FullMethodName = "/zenflux.ChatService/ReconnectStream"
	ChatService_ChatMockStream_FullMethodName  = "/zenflux.ChatService/ChatMockStream"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== Chat 服务（对应 routers/chat.py） ====================
type ChatServiceClient interface {
	// 聊天接口（同步模式）
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	// 聊天接口（流式模式）
	ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	// 重连到已存在的会话（流式）
	ReconnectStream(ctx context.Context, in *ReconnectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	// Mock 流式接口（用于前端测试）
	ChatMockStream(ctx context.Context, in *ChatMockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, ChatService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], ChatService_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_ChatStreamClient = grpc.ServerStreamingClient[ChatEvent]

func (c *chatServiceClient) ReconnectStream(ctx context.Context, in *ReconnectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[1], ChatService_ReconnectStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReconnectRequest, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_ReconnectStreamClient = grpc.ServerStreamingClient[ChatEvent]

func (c *chatServiceClient) ChatMockStream(ctx context.Context, in *ChatMockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[2], ChatService_ChatMockStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatMockRequest, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_ChatMockStreamClient = grpc.ServerStreamingClient[ChatEvent]

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
//
// ==================== Chat 服务（对应 routers/chat.py） ====================
type ChatServiceServer interface {
	// 聊天接口（同步模式）
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	// 聊天接口（流式模式）
	ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error
	// 重连到已存在的会话（流式）
	ReconnectStream(*ReconnectRequest, grpc.ServerStreamingServer[ChatEvent]) error
	// Mock 流式接口（用于前端测试）
	ChatMockStream(*ChatMockRequest, grpc.ServerStreamingServer[ChatEvent]) error
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedChatServiceServer) ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedChatServiceServer) ReconnectStream(*ReconnectRequest, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method ReconnectStream not implemented")
}
func (UnimplementedChatServiceServer) ChatMockStream(*ChatMockRequest, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method ChatMockStream not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call panics, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).ChatStream(m, &grpc.GenericServerStream[ChatRequest, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_ChatStreamServer = grpc.ServerStreamingServer[ChatEvent]

func _ChatService_ReconnectStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReconnectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).ReconnectStream(m, &grpc.GenericServerStream[ReconnectRequest, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_ReconnectStreamServer = grpc.ServerStreamingServer[ChatEvent]

func _ChatService_ChatMockStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatMockRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).ChatMockStream(m, &grpc.GenericServerStream[ChatMockRequest, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_ChatMockStreamServer = grpc.ServerStreamingServer[ChatEvent]

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zenflux.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _ChatService_Chat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _ChatService_ChatStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReconnectStream",
			Handler:       _ChatService_ReconnectStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ChatMockStream",
			Handler:       _ChatService_ChatMockStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tool_service.proto",
}

const (
	SessionService_GetSessionStatus_FullMethodName = "/zenflux.SessionService/GetSessionStatus"
	SessionService_GetSessionEvents_FullMethodName = "/zenflux.SessionService/GetSessionEvents"
	SessionService_GetUserSessions_FullMethodName  = "/zenflux.SessionService/GetUserSessions"
	SessionService_StopSession_FullMethodName      = "/zenflux.SessionService/StopSession"
	SessionService_EndSession_FullMethodName       = "/zenflux.SessionService/EndSession"
	SessionService_ListSessions_FullMethodName     = "/zenflux.SessionService/ListSessions"
)

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== Session 服务（会话管理） ====================
type SessionServiceClient interface {
	// 获取会话状态
	GetSessionStatus(ctx context.Context, in *SessionStatusRequest, opts ...grpc.CallOption) (*SessionStatusResponse, error)
	// 获取会话事件列表
	GetSessionEvents(ctx context.Context, in *SessionEventsRequest, opts ...grpc.CallOption) (*SessionEventsResponse, error)
	// 获取用户的所有活跃会话
	GetUserSessions(ctx context.Context, in *UserSessionsRequest, opts ...grpc.CallOption) (*UserSessionsResponse, error)
	// 停止会话
	StopSession(ctx context.Context, in *StopSessionRequest, opts ...grpc.CallOption) (*StopSessionResponse, error)
	// 结束会话
	EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error)
	// 列出所有活跃会话
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
}

type sessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionServiceClient(cc grpc.ClientConnInterface) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) GetSessionStatus(ctx context.Context, in *SessionStatusRequest, opts ...grpc.CallOption) (*SessionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionStatusResponse)
	err := c.cc.Invoke(ctx, SessionService_GetSessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) GetSessionEvents(ctx context.Context, in *SessionEventsRequest, opts ...grpc.CallOption) (*SessionEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionEventsResponse)
	err := c.cc.Invoke(ctx, SessionService_GetSessionEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) GetUserSessions(ctx context.Context, in *UserSessionsRequest, opts ...grpc.CallOption) (*UserSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserSessionsResponse)
	err := c.cc.Invoke(ctx, SessionService_GetUserSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) StopSession(ctx context.Context, in *StopSessionRequest, opts ...grpc.CallOption) (*StopSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopSessionResponse)
	err := c.cc.Invoke(ctx, SessionService_StopSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndSessionResponse)
	err := c.cc.Invoke(ctx, SessionService_EndSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, SessionService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServiceServer is the server API for SessionService service.
// All implementations must embed UnimplementedSessionServiceServer
// for forward compatibility.
//
// ==================== Session 服务（会话管理） ====================
type SessionServiceServer interface {
	// 获取会话状态
	GetSessionStatus(context.Context, *SessionStatusRequest) (*SessionStatusResponse, error)
	// 获取会话事件列表
	GetSessionEvents(context.Context, *SessionEventsRequest) (*SessionEventsResponse, error)
	// 获取用户的所有活跃会话
	GetUserSessions(context.Context, *UserSessionsRequest) (*UserSessionsResponse, error)
	// 停止会话
	StopSession(context.Context, *StopSessionRequest) (*StopSessionResponse, error)
	// 结束会话
	EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error)
	// 列出所有活跃会话
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	mustEmbedUnimplementedSessionServiceServer()
}

// UnimplementedSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionServiceServer struct{}

func (UnimplementedSessionServiceServer) GetSessionStatus(context.Context, *SessionStatusRequest) (*SessionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionStatus not implemented")
}
func (UnimplementedSessionServiceServer) GetSessionEvents(context.Context, *SessionEventsRequest) (*SessionEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionEvents not implemented")
}
func (UnimplementedSessionServiceServer) GetUserSessions(context.Context, *UserSessionsRequest) (*UserSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSessions not implemented")
}
func (UnimplementedSessionServiceServer) StopSession(context.Context, *StopSessionRequest) (*StopSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopSession not implemented")
}
func (UnimplementedSessionServiceServer) EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndSession not implemented")
}
func (UnimplementedSessionServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedSessionServiceServer) mustEmbedUnimplementedSessionServiceServer() {}
func (UnimplementedSessionServiceServer) testEmbeddedByValue()                        {}

// UnsafeSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServiceServer will
// result in compilation errors.
type UnsafeSessionServiceServer interface {
	mustEmbedUnimplementedSessionServiceServer()
}

func RegisterSessionServiceServer(s grpc.ServiceRegistrar, srv SessionServiceServer) {
	// If the following call panics, it indicates UnimplementedSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionService_ServiceDesc, srv)
}

func _SessionService_GetSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_GetSessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetSessionStatus(ctx, req.(*SessionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_GetSessionEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetSessionEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_GetSessionEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetSessionEvents(ctx, req.(*SessionEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_GetUserSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetUserSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_GetUserSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetUserSessions(ctx, req.(*UserSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_StopSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).StopSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_StopSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).StopSession(ctx, req.(*StopSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_EndSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).EndSession(ctx, req.(*EndSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionService_ServiceDesc is the grpc.ServiceDesc for SessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zenflux.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSessionStatus",
			Handler:    _SessionService_GetSessionStatus_Handler,
		},
		{
			MethodName: "GetSessionEvents",
			Handler:    _SessionService_GetSessionEvents_Handler,
		},
		{
			MethodName: "GetUserSessions",
			Handler:    _SessionService_GetUserSessions_Handler,
		},
		{
			MethodName: "StopSession",
			Handler:    _SessionService_StopSession_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _SessionService_EndSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _SessionService_ListSessions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tool_service.proto",
}

const (
	ToolService_ExecuteTool_FullMethodName       = "/zenflux.ToolService/ExecuteTool"
	ToolService_ExecuteToolStream_FullMethodName = "/zenflux.ToolService/ExecuteToolStream"
	ToolService_ExecuteToolBatch_FullMethodName  = "/zenflux.ToolService/ExecuteToolBatch"
)

// ToolServiceClient is the client API for ToolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== Tool 服务（工具执行） ====================
type ToolServiceClient interface {
	// 执行工具（同步模式）
	ExecuteTool(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResponse, error)
	// 执行工具（流式模式）
	ExecuteToolStream(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ToolChunk], error)
	// 批量执行工具
	ExecuteToolBatch(ctx context.Context, in *ToolBatchRequest, opts ...grpc.CallOption) (*ToolBatchResponse, error)
}

type toolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolServiceClient(cc grpc.ClientConnInterface) ToolServiceClient {
	return &toolServiceClient{cc}
}

func (c *toolServiceClient) ExecuteTool(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolResponse)
	err := c.cc.Invoke(ctx, ToolService_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) ExecuteToolStream(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ToolChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ToolService_ServiceDesc.Streams[0], ToolService_ExecuteToolStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ToolRequest, ToolChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolService_ExecuteToolStreamClient = grpc.ServerStreamingClient[ToolChunk]

func (c *toolServiceClient) ExecuteToolBatch(ctx context.Context, in *ToolBatchRequest, opts ...grpc.CallOption) (*ToolBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolBatchResponse)
	err := c.cc.Invoke(ctx, ToolService_ExecuteToolBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolServiceServer is the server API for ToolService service.
// All implementations must embed UnimplementedToolServiceServer
// for forward compatibility.
//
// ==================== Tool 服务（工具执行） ====================
type ToolServiceServer interface {
	// 执行工具（同步模式）
	ExecuteTool(context.Context, *ToolRequest) (*ToolResponse, error)
	// 执行工具（流式模式）
	ExecuteToolStream(*ToolRequest, grpc.ServerStreamingServer[ToolChunk]) error
	// 批量执行工具
	ExecuteToolBatch(context.Context, *ToolBatchRequest) (*ToolBatchResponse, error)
	mustEmbedUnimplementedToolServiceServer()
}

// UnimplementedToolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolServiceServer struct{}

func (UnimplementedToolServiceServer) ExecuteTool(context.Context, *ToolRequest) (*ToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedToolServiceServer) ExecuteToolStream(*ToolRequest, grpc.ServerStreamingServer[ToolChunk]) error {
	return status.Error(codes.Unimplemented, "method ExecuteToolStream not implemented")
}
func (UnimplementedToolServiceServer) ExecuteToolBatch(context.Context, *ToolBatchRequest) (*ToolBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteToolBatch not implemented")
}
func (UnimplementedToolServiceServer) mustEmbedUnimplementedToolServiceServer() {}
func (UnimplementedToolServiceServer) testEmbeddedByValue()                     {}

// UnsafeToolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolServiceServer will
// result in compilation errors.
type UnsafeToolServiceServer interface {
	mustEmbedUnimplementedToolServiceServer()
}

func RegisterToolServiceServer(s grpc.ServiceRegistrar, srv ToolServiceServer) {
	// If the following call panics, it indicates UnimplementedToolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolService_ServiceDesc, srv)
}

func _ToolService_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).ExecuteTool(ctx, req.(*ToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_ExecuteToolStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ToolRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ToolServiceServer).ExecuteToolStream(m, &grpc.GenericServerStream[ToolRequest, ToolChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolService_ExecuteToolStreamServer = grpc.ServerStreamingServer[ToolChunk]

func _ToolService_ExecuteToolBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).ExecuteToolBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_ExecuteToolBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).ExecuteToolBatch(ctx, req.(*ToolBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolService_ServiceDesc is the grpc.ServiceDesc for ToolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zenflux.ToolService",
	HandlerType: (*ToolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTool",
			Handler:    _ToolService_ExecuteTool_Handler,
		},
		{
			MethodName: "ExecuteToolBatch",
			Handler:    _ToolService_ExecuteToolBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteToolStream",
			Handler:       _ToolService_ExecuteToolStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tool_service.proto",
}

const (
	AgentService_ExecuteTask_FullMethodName       = "/zenflux.AgentService/ExecuteTask"
	AgentService_ExecuteTaskStream_FullMethodName = "/zenflux.AgentService/ExecuteTaskStream"
	AgentService_GetAgentStatus_FullMethodName    = "/zenflux.AgentService/GetAgentStatus"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== Agent 服务（多 Agent 协作） ====================
type AgentServiceClient interface {
	// 执行 Agent 任务
	ExecuteTask(ctx context.Context, in *AgentTaskRequest, opts ...grpc.CallOption) (*AgentTaskResponse, error)
	// 流式执行 Agent 任务
	ExecuteTaskStream(ctx context.Context, in *AgentTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentTaskEvent], error)
	// 获取 Agent 状态
	GetAgentStatus(ctx context.Context, in *AgentStatusRequest, opts ...grpc.CallOption) (*AgentStatusResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) ExecuteTask(ctx context.Context, in *AgentTaskRequest, opts ...grpc.CallOption) (*AgentTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentTaskResponse)
	err := c.cc.Invoke(ctx, AgentService_ExecuteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ExecuteTaskStream(ctx context.Context, in *AgentTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentTaskEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_ExecuteTaskStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentTaskRequest, AgentTaskEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ExecuteTaskStreamClient = grpc.ServerStreamingClient[AgentTaskEvent]

func (c *agentServiceClient) GetAgentStatus(ctx context.Context, in *AgentStatusRequest, opts ...grpc.CallOption) (*AgentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_GetAgentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// ==================== Agent 服务（多 Agent 协作） ====================
type AgentServiceServer interface {
	// 执行 Agent 任务
	ExecuteTask(context.Context, *AgentTaskRequest) (*AgentTaskResponse, error)
	// 流式执行 Agent 任务
	ExecuteTaskStream(*AgentTaskRequest, grpc.ServerStreamingServer[AgentTaskEvent]) error
	// 获取 Agent 状态
	GetAgentStatus(context.Context, *AgentStatusRequest) (*AgentStatusResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) ExecuteTask(context.Context, *AgentTaskRequest) (*AgentTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedAgentServiceServer) ExecuteTaskStream(*AgentTaskRequest, grpc.ServerStreamingServer[AgentTaskEvent]) error {
	return status.Error(codes.Unimplemented, "method ExecuteTaskStream not implemented")
}
func (UnimplementedAgentServiceServer) GetAgentStatus(context.Context, *AgentStatusRequest) (*AgentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentStatus not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_ExecuteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ExecuteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ExecuteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ExecuteTask(ctx, req.(*AgentTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ExecuteTaskStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AgentTaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).ExecuteTaskStream(m, &grpc.GenericServerStream[AgentTaskRequest, AgentTaskEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ExecuteTaskStreamServer = grpc.ServerStreamingServer[AgentTaskEvent]

func _AgentService_GetAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgentStatus(ctx, req.(*AgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zenflux.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTask",
			Handler:    _AgentService_ExecuteTask_Handler,
		},
		{
			MethodName: "GetAgentStatus",
			Handler:    _AgentService_GetAgentStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteTaskStream",
			Handler:       _AgentService_ExecuteTaskStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tool_service.proto",
}

const (
	ConfirmationService_GetPendingRequests_FullMethodName = "/zenflux.ConfirmationService/GetPendingRequests"
	ConfirmationService_SubmitResponse_FullMethodName     = "/zenflux.ConfirmationService/SubmitResponse"
	ConfirmationService_CancelRequest_FullMethodName      = "/zenflux.ConfirmationService/CancelRequest"
	ConfirmationService_GetStats_FullMethodName           = "/zenflux.ConfirmationService/GetStats"
	ConfirmationService_WatchConfirmations_FullMethodName = "/zenflux.ConfirmationService/WatchConfirmations"
)

// ConfirmationServiceClient is the client API for ConfirmationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== Confirmation 服务（HITL 确认） ====================
type ConfirmationServiceClient interface {
	// 获取待处理的确认请求
	GetPendingRequests(ctx context.Context, in *GetPendingRequestsRequest, opts ...grpc.CallOption) (*GetPendingRequestsResponse, error)
	// 提交确认响应
	SubmitResponse(ctx context.Context, in *SubmitConfirmationRequest, opts ...grpc.CallOption) (*SubmitConfirmationResponse, error)
	// 取消确认请求
	CancelRequest(ctx context.Context, in *CancelConfirmationRequest, opts ...grpc.CallOption) (*CancelConfirmationResponse, error)
	// 获取统计信息
	GetStats(ctx context.Context, in *ConfirmationStatsRequest, opts ...grpc.CallOption) (*ConfirmationStatsResponse, error)
	// 监听确认请求（流式，用于实时接收新的确认请求）
	WatchConfirmations(ctx context.Context, in *WatchConfirmationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfirmationEvent], error)
}

type confirmationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfirmationServiceClient(cc grpc.ClientConnInterface) ConfirmationServiceClient {
	return &confirmationServiceClient{cc}
}

func (c *confirmationServiceClient) GetPendingRequests(ctx context.Context, in *GetPendingRequestsRequest, opts ...grpc.CallOption) (*GetPendingRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingRequestsResponse)
	err := c.cc.Invoke(ctx, ConfirmationService_GetPendingRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *confirmationServiceClient) SubmitResponse(ctx context.Context, in *SubmitConfirmationRequest, opts ...grpc.CallOption) (*SubmitConfirmationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitConfirmationResponse)
	err := c.cc.Invoke(ctx, ConfirmationService_SubmitResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *confirmationServiceClient) CancelRequest(ctx context.Context, in *CancelConfirmationRequest, opts ...grpc.CallOption) (*CancelConfirmationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelConfirmationResponse)
	err := c.cc.Invoke(ctx, ConfirmationService_CancelRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *confirmationServiceClient) GetStats(ctx context.Context, in *ConfirmationStatsRequest, opts ...grpc.CallOption) (*ConfirmationStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmationStatsResponse)
	err := c.cc.Invoke(ctx, ConfirmationService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *confirmationServiceClient) WatchConfirmations(ctx context.Context, in *WatchConfirmationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfirmationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfirmationService_ServiceDesc.Streams[0], ConfirmationService_WatchConfirmations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchConfirmationsRequest, ConfirmationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfirmationService_WatchConfirmationsClient = grpc.ServerStreamingClient[ConfirmationEvent]

// ConfirmationServiceServer is the server API for ConfirmationService service.
// All implementations must embed UnimplementedConfirmationServiceServer
// for forward compatibility.
//
// ==================== Confirmation 服务（HITL 确认） ====================
type ConfirmationServiceServer interface {
	// 获取待处理的确认请求
	GetPendingRequests(context.Context, *GetPendingRequestsRequest) (*GetPendingRequestsResponse, error)
	// 提交确认响应
	SubmitResponse(context.Context, *SubmitConfirmationRequest) (*SubmitConfirmationResponse, error)
	// 取消确认请求
	CancelRequest(context.Context, *CancelConfirmationRequest) (*CancelConfirmationResponse, error)
	// 获取统计信息
	GetStats(context.Context, *ConfirmationStatsRequest) (*ConfirmationStatsResponse, error)
	// 监听确认请求（流式，用于实时接收新的确认请求）
	WatchConfirmations(*WatchConfirmationsRequest, grpc.ServerStreamingServer[ConfirmationEvent]) error
	mustEmbedUnimplementedConfirmationServiceServer()
}

// UnimplementedConfirmationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfirmationServiceServer struct{}

func (UnimplementedConfirmationServiceServer) GetPendingRequests(context.Context, *GetPendingRequestsRequest) (*GetPendingRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingRequests not implemented")
}
func (UnimplementedConfirmationServiceServer) SubmitResponse(context.Context, *SubmitConfirmationRequest) (*SubmitConfirmationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResponse not implemented")
}
func (UnimplementedConfirmationServiceServer) CancelRequest(context.Context, *CancelConfirmationRequest) (*CancelConfirmationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRequest not implemented")
}
func (UnimplementedConfirmationServiceServer) GetStats(context.Context, *ConfirmationStatsRequest) (*ConfirmationStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedConfirmationServiceServer) WatchConfirmations(*WatchConfirmationsRequest, grpc.ServerStreamingServer[ConfirmationEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchConfirmations not implemented")
}
func (UnimplementedConfirmationServiceServer) mustEmbedUnimplementedConfirmationServiceServer() {}
func (UnimplementedConfirmationServiceServer) testEmbeddedByValue()                             {}

// UnsafeConfirmationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfirmationServiceServer will
// result in compilation errors.
type UnsafeConfirmationServiceServer interface {
	mustEmbedUnimplementedConfirmationServiceServer()
}

func RegisterConfirmationServiceServer(s grpc.ServiceRegistrar, srv ConfirmationServiceServer) {
	// If the following call panics, it indicates UnimplementedConfirmationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfirmationService_ServiceDesc, srv)
}

func _ConfirmationService_GetPendingRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfirmationServiceServer).GetPendingRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfirmationService_GetPendingRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfirmationServiceServer).GetPendingRequests(ctx, req.(*GetPendingRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfirmationService_SubmitResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfirmationServiceServer).SubmitResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfirmationService_SubmitResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfirmationServiceServer).SubmitResponse(ctx, req.(*SubmitConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfirmationService_CancelRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfirmationServiceServer).CancelRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfirmationService_CancelRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfirmationServiceServer).CancelRequest(ctx, req.(*CancelConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfirmationService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmationStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfirmationServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfirmationService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfirmationServiceServer).GetStats(ctx, req.(*ConfirmationStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfirmationService_WatchConfirmations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchConfirmationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfirmationServiceServer).WatchConfirmations(m, &grpc.GenericServerStream[WatchConfirmationsRequest, ConfirmationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfirmationService_WatchConfirmationsServer = grpc.ServerStreamingServer[ConfirmationEvent]

// ConfirmationService_ServiceDesc is the grpc.ServiceDesc for ConfirmationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfirmationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zenflux.ConfirmationService",
	HandlerType: (*ConfirmationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPendingRequests",
			Handler:    _ConfirmationService_GetPendingRequests_Handler,
		},
		{
			MethodName: "SubmitResponse",
			Handler:    _ConfirmationService_SubmitResponse_Handler,
		},
		{
			MethodName: "CancelRequest",
			Handler:    _ConfirmationService_CancelRequest_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _ConfirmationService_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchConfirmations",
			Handler:       _ConfirmationService_WatchConfirmations_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tool_service.proto",
}

const (
	SandboxService_GetStatus_FullMethodName   = "/zenflux.SandboxService/GetStatus"
	SandboxService_Init_FullMethodName        = "/zenflux.SandboxService/Init"
	SandboxService_Pause_FullMethodName       = "/zenflux.SandboxService/Pause"
	SandboxService_Resume_FullMethodName      = "/zenflux.SandboxService/Resume"
	SandboxService_Kill_FullMethodName        = "/zenflux.SandboxService/Kill"
	SandboxService_RunProject_FullMethodName  = "/zenflux.SandboxService/RunProject"
	SandboxService_StopProject_FullMethodName = "/zenflux.SandboxService/StopProject"
	SandboxService_GetLogs_FullMethodName     = "/zenflux.SandboxService/GetLogs"
	SandboxService_RunCommand_FullMethodName  = "/zenflux.SandboxService/RunCommand"
	SandboxService_ListFiles_FullMethodName   = "/zenflux.SandboxService/ListFiles"
)

// SandboxServiceClient is the client API for SandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== Sandbox 服务（沙盒管理） ====================
type SandboxServiceClient interface {
	// 获取沙盒状态
	GetStatus(ctx context.Context, in *SandboxStatusRequest, opts ...grpc.CallOption) (*SandboxStatusResponse, error)
	// 初始化沙盒
	Init(ctx context.Context, in *SandboxInitRequest, opts ...grpc.CallOption) (*SandboxStatusResponse, error)
	// 暂停沙盒
	Pause(ctx context.Context, in *SandboxPauseRequest, opts ...grpc.CallOption) (*SandboxOperationResponse, error)
	// 恢复沙盒
	Resume(ctx context.Context, in *SandboxResumeRequest, opts ...grpc.CallOption) (*SandboxStatusResponse, error)
	// 终止沙盒
	Kill(ctx context.Context, in *SandboxKillRequest, opts ...grpc.CallOption) (*SandboxOperationResponse, error)
	// 运行项目
	RunProject(ctx context.Context, in *SandboxRunProjectRequest, opts ...grpc.CallOption) (*SandboxRunProjectResponse, error)
	// 停止项目
	StopProject(ctx context.Context, in *SandboxStopProjectRequest, opts ...grpc.CallOption) (*SandboxOperationResponse, error)
	// 获取项目日志
	GetLogs(ctx context.Context, in *SandboxLogsRequest, opts ...grpc.CallOption) (*SandboxLogsResponse, error)
	// 执行命令
	RunCommand(ctx context.Context, in *SandboxCommandRequest, opts ...grpc.CallOption) (*SandboxCommandResponse, error)
	// 获取文件列表
	ListFiles(ctx context.Context, in *SandboxListFilesRequest, opts ...grpc.CallOption) (*SandboxListFilesResponse, error)
}

type sandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxServiceClient(cc grpc.ClientConnInterface) SandboxServiceClient {
	return &sandboxServiceClient{cc}
}

func (c *sandboxServiceClient) GetStatus(ctx context.Context, in *SandboxStatusRequest, opts ...grpc.CallOption) (*SandboxStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxStatusResponse)
	err := c.cc.Invoke(ctx, SandboxService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Init(ctx context.Context, in *SandboxInitRequest, opts ...grpc.CallOption) (*SandboxStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxStatusResponse)
	err := c.cc.Invoke(ctx, SandboxService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Pause(ctx context.Context, in *SandboxPauseRequest, opts ...grpc.CallOption) (*SandboxOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxOperationResponse)
	err := c.cc.Invoke(ctx, SandboxService_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Resume(ctx context.Context, in *SandboxResumeRequest, opts ...grpc.CallOption) (*SandboxStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxStatusResponse)
	err := c.cc.Invoke(ctx, SandboxService_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) Kill(ctx context.Context, in *SandboxKillRequest, opts ...grpc.CallOption) (*SandboxOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxOperationResponse)
	err := c.cc.Invoke(ctx, SandboxService_Kill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) RunProject(ctx context.Context, in *SandboxRunProjectRequest, opts ...grpc.CallOption) (*SandboxRunProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxRunProjectResponse)
	err := c.cc.Invoke(ctx, SandboxService_RunProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) StopProject(ctx context.Context, in *SandboxStopProjectRequest, opts ...grpc.CallOption) (*SandboxOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxOperationResponse)
	err := c.cc.Invoke(ctx, SandboxService_StopProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetLogs(ctx context.Context, in *SandboxLogsRequest, opts ...grpc.CallOption) (*SandboxLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxLogsResponse)
	err := c.cc.Invoke(ctx, SandboxService_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) RunCommand(ctx context.Context, in *SandboxCommandRequest, opts ...grpc.CallOption) (*SandboxCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxCommandResponse)
	err := c.cc.Invoke(ctx, SandboxService_RunCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ListFiles(ctx context.Context, in *SandboxListFilesRequest, opts ...grpc.CallOption) (*SandboxListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxListFilesResponse)
	err := c.cc.Invoke(ctx, SandboxService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxServiceServer is the server API for SandboxService service.
// All implementations must embed UnimplementedSandboxServiceServer
// for forward compatibility.
//
// ==================== Sandbox 服务（沙盒管理） ====================
type SandboxServiceServer interface {
	// 获取沙盒状态
	GetStatus(context.Context, *SandboxStatusRequest) (*SandboxStatusResponse, error)
	// 初始化沙盒
	Init(context.Context, *SandboxInitRequest) (*SandboxStatusResponse, error)
	// 暂停沙盒
	Pause(context.Context, *SandboxPauseRequest) (*SandboxOperationResponse, error)
	// 恢复沙盒
	Resume(context.Context, *SandboxResumeRequest) (*SandboxStatusResponse, error)
	// 终止沙盒
	Kill(context.Context, *SandboxKillRequest) (*SandboxOperationResponse, error)
	// 运行项目
	RunProject(context.Context, *SandboxRunProjectRequest) (*SandboxRunProjectResponse, error)
	// 停止项目
	StopProject(context.Context, *SandboxStopProjectRequest) (*SandboxOperationResponse, error)
	// 获取项目日志
	GetLogs(context.Context, *SandboxLogsRequest) (*SandboxLogsResponse, error)
	// 执行命令
	RunCommand(context.Context, *SandboxCommandRequest) (*SandboxCommandResponse, error)
	// 获取文件列表
	ListFiles(context.Context, *SandboxListFilesRequest) (*SandboxListFilesResponse, error)
	mustEmbedUnimplementedSandboxServiceServer()
}

// UnimplementedSandboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxServiceServer struct{}

func (UnimplementedSandboxServiceServer) GetStatus(context.Context, *SandboxStatusRequest) (*SandboxStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedSandboxServiceServer) Init(context.Context, *SandboxInitRequest) (*SandboxStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedSandboxServiceServer) Pause(context.Context, *SandboxPauseRequest) (*SandboxOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedSandboxServiceServer) Resume(context.Context, *SandboxResumeRequest) (*SandboxStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedSandboxServiceServer) Kill(context.Context, *SandboxKillRequest) (*SandboxOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Kill not implemented")
}
func (UnimplementedSandboxServiceServer) RunProject(context.Context, *SandboxRunProjectRequest) (*SandboxRunProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunProject not implemented")
}
func (UnimplementedSandboxServiceServer) StopProject(context.Context, *SandboxStopProjectRequest) (*SandboxOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopProject not implemented")
}
func (UnimplementedSandboxServiceServer) GetLogs(context.Context, *SandboxLogsRequest) (*SandboxLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedSandboxServiceServer) RunCommand(context.Context, *SandboxCommandRequest) (*SandboxCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunCommand not implemented")
}
func (UnimplementedSandboxServiceServer) ListFiles(context.Context, *SandboxListFilesRequest) (*SandboxListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedSandboxServiceServer) mustEmbedUnimplementedSandboxServiceServer() {}
func (UnimplementedSandboxServiceServer) testEmbeddedByValue()                        {}

// UnsafeSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServiceServer will
// result in compilation errors.
type UnsafeSandboxServiceServer interface {
	mustEmbedUnimplementedSandboxServiceServer()
}

func RegisterSandboxServiceServer(s grpc.ServiceRegistrar, srv SandboxServiceServer) {
	// If the following call panics, it indicates UnimplementedSandboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxService_ServiceDesc, srv)
}

func _SandboxService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetStatus(ctx, req.(*SandboxStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Init(ctx, req.(*SandboxInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Pause(ctx, req.(*SandboxPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Resume(ctx, req.(*SandboxResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxKillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Kill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Kill(ctx, req.(*SandboxKillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_RunProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxRunProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).RunProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_RunProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).RunProject(ctx, req.(*SandboxRunProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_StopProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxStopProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).StopProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_StopProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).StopProject(ctx, req.(*SandboxStopProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetLogs(ctx, req.(*SandboxLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_RunCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).RunCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_RunCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).RunCommand(ctx, req.(*SandboxCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ListFiles(ctx, req.(*SandboxListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxService_ServiceDesc is the grpc.ServiceDesc for SandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zenflux.SandboxService",
	HandlerType: (*SandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _SandboxService_GetStatus_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _SandboxService_Init_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _SandboxService_Pause_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _SandboxService_Resume_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _SandboxService_Kill_Handler,
		},
		{
			MethodName: "RunProject",
			Handler:    _SandboxService_RunProject_Handler,
		},
		{
			MethodName: "StopProject",
			Handler:    _SandboxService_StopProject_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _SandboxService_GetLogs_Handler,
		},
		{
			MethodName: "RunCommand",
			Handler:    _SandboxService_RunCommand_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _SandboxService_ListFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tool_service.proto",
}
